// Simple icons using text/emoji - no external dependencies needed
// This keeps things simple for React beginners

export const MenuIcon = () => <span>☰</span>
export const HomeIcon = () => <span>🏠</span>
export const UserIcon = () => <span>👤</span>
export const SearchIcon = () => <span>🔍</span>
export const SettingsIcon = () => <span>⚙️</span>
export const AddIcon = () => <span>➕</span>
export const MinusIcon = () => <span>➖</span>
export const CloseIcon = () => <span>✕</span>
export const CheckIcon = () => <span>✓</span>
export const EditIcon = () => <span>✏️</span>
export const TrashIcon = () => <span>🗑️</span>
export const ViewIcon = () => <span>👁️</span>
export const SaveIcon = () => <span>💾</span>
export const DownloadIcon = () => <span>⬇️</span>
export const UploadIcon = () => <span>⬆️</span>
export const RefreshIcon = () => <span>🔄</span>
export const FilterIcon = () => <span>🔽</span>
export const ArrowRightIcon = () => <span>→</span>
export const ArrowLeftIcon = () => <span>←</span>
export const ArrowUpIcon = () => <span>↑</span>
export const ArrowDownIcon = () => <span>↓</span>
export const CaretRightIcon = () => <span>›</span>
export const CaretDownIcon = () => <span>⌄</span>
export const ChevronRightIcon = () => <span>›</span>
export const ChevronDownIcon = () => <span>⌄</span>
export const ChevronUpIcon = () => <span>⌃</span>
export const ChevronLeftIcon = () => <span>‹</span>
export const SuccessIcon = () => <span>✅</span>
export const ErrorIcon = () => <span>❌</span>
export const WarningIcon = () => <span>⚠️</span>
export const InfoIcon = () => <span>ℹ️</span>
export const HelpIcon = () => <span>❓</span>
export const NotificationIcon = () => <span>🔔</span>
export const LockIcon = () => <span>🔒</span>
export const UserAddIcon = () => <span>➕👤</span>
export const LogoutIcon = () => <span>🚪</span>
export const PassportIcon = () => <span>📘</span>
export const PlaneIcon = () => <span>✈️</span>
export const CarIcon = () => <span>🚗</span>
export const TrainIcon = () => <span>🚂</span>
export const BusIcon = () => <span>🚌</span>
export const DriveIcon = () => <span>🚙</span>
export const LocationIcon = () => <span>📍</span>
export const MapIcon = () => <span>🗺️</span>
export const GlobeIcon = () => <span>🌐</span>
export const FlagIcon = () => <span>🚩</span>
export const FileIcon = () => <span>📄</span>
export const MoneyIcon = () => <span>💰</span>
export const CreditCardIcon = () => <span>💳</span>
export const CartIcon = () => <span>🛒</span>
export const BookmarkIcon = () => <span>🔖</span>
export const CalendarIcon = () => <span>📅</span>
export const CalendarDateIcon = () => <span>📆</span>
export const ClockIcon = () => <span>🕐</span>
export const TimerIcon = () => <span>⏱️</span>
export const StopwatchIcon = () => <span>⏱️</span>
export const FolderIcon = () => <span>📁</span>
export const DocumentIcon = () => <span>📄</span>
export const ImageIcon = () => <span>🖼️</span>
export const PrinterIcon = () => <span>🖨️</span>
export const DesktopIcon = () => <span>🖥️</span>
export const LaptopIcon = () => <span>💻</span>
export const DatabaseIcon = () => <span>🗄️</span>
export const ServerIcon = () => <span>🖥️</span>
export const CloudIcon = () => <span>☁️</span>
export const PlayIcon = () => <span>▶️</span>
export const PauseIcon = () => <span>⏸️</span>
export const StopIcon = () => <span>⏹️</span>
export const RecordIcon = () => <span>⏺️</span>
export const NextIcon = () => <span>⏭️</span>
export const PreviousIcon = () => <span>⏮️</span>
export const ShuffleIcon = () => <span>🔀</span>
export const RepeatIcon = () => <span>🔁</span>
export const VolumeIcon = () => <span>🔊</span>
export const SpeakerIcon = () => <span>🔈</span>
export const HeadphonesIcon = () => <span>🎧</span>
export const MicrophoneIcon = () => <span>🎤</span>
export const MicIcon = () => <span>🎤</span>
export const VideoIcon = () => <span>📹</span>
export const StarIcon = () => <span>⭐</span>
export const HeartIcon = () => <span>❤️</span>
export const SmileIcon = () => <span>😊</span>
export const FrownIcon = () => <span>😞</span>
export const MehIcon = () => <span>😐</span>
export const EyeIcon = () => <span>👁️</span>
export const AtIcon = () => <span>@</span>
export const HashtagIcon = () => <span>#</span>
export const TagIcon = () => <span>🏷️</span>
export const MailIcon = () => <span>📧</span>
export const PhoneIcon = () => <span>📞</span>
export const ChatIcon = () => <span>💬</span>
export const SendIcon = () => <span>📤</span>
export const BullhornIcon = () => <span>📢</span>
export const BuildingIcon = () => <span>🏢</span>
export const ShopIcon = () => <span>🏪</span>
export const BankIcon = () => <span>🏦</span>
export const HospitalIcon = () => <span>🏥</span>
export const SchoolIcon = () => <span>🏫</span>
export const UniversityIcon = () => <span>🏛️</span>
export const GovernmentIcon = () => <span>🏛️</span>
export const FactoryIcon = () => <span>🏭</span>
export const ShieldIcon = () => <span>🛡️</span>
export const UmbrellaIcon = () => <span>☂️</span>
export const FireIcon = () => <span>🔥</span>
export const PoliceIcon = () => <span>👮</span>
export const AmbulanceIcon = () => <span>🚑</span>
export const SunIcon = () => <span>☀️</span>
export const MoonIcon = () => <span>🌙</span>
export const CloudOutlineIcon = () => <span>☁️</span>
export const CloudSunIcon = () => <span>⛅</span>
export const RainIcon = () => <span>🌧️</span>
export const SnowIcon = () => <span>❄️</span>
export const ThunderIcon = () => <span>⛈️</span>
export const CoffeeIcon = () => <span>☕</span>
export const GlassIcon = () => <span>🥃</span>
export const CupIcon = () => <span>🥤</span>
export const BeerIcon = () => <span>🍺</span>
export const FoodIcon = () => <span>🍴</span>
export const PizzaIcon = () => <span>🍕</span>
export const BurgerIcon = () => <span>🍔</span>
export const CakeIcon = () => <span>🎂</span>
export const HotelIcon = () => <span>🏨</span>
export const WrenchIcon = () => <span>🔧</span>
export const HammerIcon = () => <span>🔨</span>
export const ScrewdriverIcon = () => <span>🪛</span>
export const ToolsIcon = () => <span>🛠️</span>
export const CutIcon = () => <span>✂️</span>
export const GiftIcon = () => <span>🎁</span>
export const MaximizeIcon = () => <span>⛶</span>
export const MinimizeIcon = () => <span>−</span>
export const Maximize2Icon = () => <span>⛶</span>
export const Minimize2Icon = () => <span>−</span>
export const ResizeIcon = () => <span>⤡</span>
export const ZoomInIcon = () => <span>🔍</span>
export const ZoomOutIcon = () => <span>🔎</span>
export const SquareIcon = () => <span>◻️</span>
export const CheckboxIcon = () => <span>☑️</span>
export const RadioButtonIcon = () => <span>🔘</span>
export const DropdownIcon = () => <span>▼</span>
export const BoldIcon = () => <span>𝐁</span>
export const ItalicIcon = () => <span>𝐼</span>
export const UnderlineIcon = () => <span>U̲</span>
export const EraserIcon = () => <span>⌫</span>
export const PenIcon = () => <span>✏️</span>
export const AlignLeftIcon = () => <span>≡</span>
export const AlignCenterIcon = () => <span>☰</span>
export const AlignRightIcon = () => <span>≡</span>
export const GridIcon = () => <span>⊞</span>
export const AppsIcon = () => <span>⊞</span>
export const BarsIcon = () => <span>☰</span>
export const HomeOutlineIcon = () => <span>🏠</span>
export const UserOutlineIcon = () => <span>👤</span>
export const ChipIcon = () => <span>🔌</span>
export const BatteryIcon = () => <span>🔋</span>
export const SortDescIcon = () => <span>🔽</span>
export const MusicNoteIcon = () => <span>♪</span>
export const MusicNotesIcon = () => <span>♫</span>
export const VisibilityIcon = () => <span>👁️</span>
export const VisibilityOffIcon = () => <span>👁️‍🗨️</span>
export const DashboardIcon = () => <span>📊</span>
export const AnalyticsIcon = () => <span>📈</span>
export const DocumentTextIcon = () => <span>📝</span>
export const WalletIcon = () => <span>👛</span>
export const SupportIcon = () => <span>🎓</span>
